title = "Beta Alpha Rho Fraternity"
baseURL = "http://betaalpharho.org/"
languageCode = "en-us"
theme = "airspace-hugo"
#themesDir = "../.."
[menu]

  [[menu.header]]
    weight = 2
    name = "Rush"
    url = "/rush"
  [[menu.header]]
    weight = 3
    name = "Executive Board"
    url = "/eboard"
  [[menu.header]]
    weight = 4
    name = "Members"
    url = "/members"
  [[menu.header]]
    weight = 5
    name = "Contact"
    url = "/contact"

  [[menu.footer]]
    weight = 1
    name = "About us"
    url = "#"
  [[menu.footer]]
    weight = 2
    name = "Contact us"
    url = "#"
  [[menu.footer]]
    weight = 3
    name = "How it works"
    url = "#"
  [[menu.footer]]
    weight = 4
    name = "Blog"
    url = "#"
  [[menu.footer]]
    weight = 5
    name = "Terms"
    url = "#"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  dateFormat = "6 January 2006"

  home = "Home"

  [params.slider]
    enable = true
    title = "BETA ALPHA RHO"
    subtitle = "University of Michigan<br>Pre-Law Fraternity"

  [params.wrapper]
    enable = true
    title = "About Us"
    #italic = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics"
    paragraph = "Beta Alpha Rho was founded in 2018 in order to provide a place of professional development and advancement for those involved with law and/or policy. We aim to attract members interested in law, policy, and social change, but we also invite anyone with a vested interest to join us. Our members come from a diverse range of backgrounds including Political Science, Computer Science, Biochemistry, Finance, and more."

  [params.rush]
    enable = true
    title = "Rush Schedule"
    subtitle = "Want to learn more? Feel free to attend one of our rush events!"
    content = "Mass Meeting: Monday, September 17th, 2018 (7-8 pm) @ Ford School, Weill 1120 <br> Speed Dating: Wednesday, September 19th, 2018 (7-9 pm) @ 6050 ISR (behind the Cube) <br> Game Night: Friday, September 21st (7-9pm) @ 3411 & 3330 MH <br> Debates: Sunday, September 23rd, 2018 (7-9 pm) @ Michigan League, Hussey Room"
    [params.feature.button]
      caption = "View Works"
      url = "#"

  [params.eboard]
    enable = true
    title = "Executive Board"
    subtitle = ""

      [[params.eboard.people]]
        img = "president.jpg"
        title = "Dim Mang - President"
        major = "Major: Political Science & History"
        year = "Year: Junior"
	about = "I would love to attend law school to eventually go into immigration law or gender discrimination. My background is shaped by the fact that I was born in Burma and raised there for 7 years, which instilled in me a desire to go into public service and do something beneficial towards my home country. On campus, I am also involved in the United Asian American Organizations (UAAO), Roosevelt Institute, Days for Girls, Uncover: A/PIA, and a string quartet."
      [[params.eboard.people]]
        img = "vp.jpg"
        title = "Caleb Hogeterp - Vice President"
        major = "Major: Community and Global Health"
        year = "Year: Junior"
	about = "Caleb’s interest in the law comes from his love of public health. He hopes to pursue both his JD and MPH after graduation, in order to work as a lawyer involved in healthcare and other public health adjacent fields. As well as being Vice President, Caleb does Environmental Health Sciences research focused on food losses, writes for SHEI magazine, is the University Communications Chair for Students for Students, and is an avid rock climber."
      [[params.eboard.people]]
        img = "secretary.jpg"
        title = "Stephanie Glenn - Secretary"
        major = "Major: Political Science"
        year = "Year: Junior"
	about = "On campus, Stephanie is involved in student government and research for the political science department. Stephanie is interested in criminal justice and education policy reform, and BAR provides the opportunity to tie together the fields of law and policy as she seeks to pursue a career in government."
      [[params.eboard.people]]
        img = "treasurer.jpg"
        title = "Elizabeth Chon - Treasurer"
        major = "Major: Public Policy"
        year = "Year: Junior"
	about = "I'm interested in the intersection between policy, technology, and economics, and I'm planning to pursue a Master's degree in Public Policy or Business Administration. My academic interests stem from my internship experience at the U.S. Department of Transportation, where I conducted research and wrote a white paper on blockchain technology and its application in automated driving systems. Aside from Beta Alpha Rho, I'm the treasurer of Gamma Rho Phi Public Policy Fraternity and I'm a member of the Roosevelt Institute. I also work at the U of M Transportation Research Institute as a research intern, where I am working on a study on aging drivers and interventions for safe mobility."
      [[params.eboard.people]]
        img = "fundraising.jpg"
        title = "Jennifer Meer - Fundraising Chair"
        major = "Major: Political Science & Sociology"
        year = "Year: Senior"
	about = "I'm also involved with the Michigan Daily and research through the Sociology Department.My interest in law stems partially from my interest in publishing -- I think copyright work is fascinating. On the flip side, I enjoy analyzing text and interpreting information, which corresponds to several aspects of law. I think reading and writing for the sake of a purpose -- to help and improve society -- is very important!"
      [[params.eboard.people]]
        img = "recruitment1.jpg"
        title = "Ivona Popova - Recruitment Chair"
        major = "Major: Political Science & Russian"
        year = "Year: Junior"
	about = ""
      [[params.eboard.people]]
        img = "recruitment2.jpg"
        title = "Sophia Kim - Recruitment Chair"
        major = "Major: History of Art & Political Science"
        year = "Year: Junior"
	about = "Sophia is interested in pursuing a career using her passion for the legal system and her backgrounds in international relations. Upon graduation, she intends to work and shortly thereafter pursue her JD."
      [[params.eboard.people]]
        img = "philanthropy.jpg"
        title = "Erin Hahn - Philanthropy Chair"
        major = "Major: International Studies"
        year = "Year: Junior"
	about = "Erin is hoping to go straight to law school after finishing her undergraduate degree, and then on to a career in immigration law. She became particularly passionate about that field while on a year abroad in Thailand, where she lived among refugee communities on the Thai / Burmese border. When she's not occupied with BAR or school, she can be found watching musical theatre or stand up comedy, riding horses, or sleeping."
      [[params.eboard.people]]
        img = "professionaldevelopment.jpg"
        title = "Kate Thompson - Professional Development Chair"
        major = "Major: Political Science & Spanish"
        year = "Year: Junior"
	about = "I first became interested in the law after the Supreme Court decided Obgerfell v. Hodges. This case made me realize how the laws and decisions made by state governments, Congress, and even the Supreme Court can impact the day to day lives of millions of Americans. On campus, I’m also involved in a Latino outreach program called Palma and a non profit organization called Students Helping Honduras."
      [[params.eboard.people]]
        img = "social.jpg"
        title = "Ashley Munger - Social Chair"
        major = "Major: Political Science & English"
        year = "Year: Junior"
	about = "Ashley is interested in studying law to become a criminal defense lawyer. She is also involved in prisoner advocacy and restorative justice work through the Prisoner Creative Arts Project (PCAP)."
      [[params.eboard.people]]
        img = "diversity.jpg"
        title = "Anu Nandi - Diversity & Inclusion Chair"
        major = "Major: Political Science"
        year = "Year: Senior"
	about = "I am interested in the law because I admire it’s ability to help people in need. Nowadays, people are heavily affected by the justice system and the law is one of the ways to see concrete change. I hope to one day be the person that can have a significant impact on someone’s life when they need help in our legal system. Outside Beta Alpha Rho, I am the president of my Multicultural Greek Sorority, Sigma Sigma Rho Sorority, Incorporated. In my free time, I also tutor kids at 826Michigan."
      [[params.eboard.people]]
        img = "pfc1.jpg"
        title = "Tatum Doyle - Professional Fraternity Council Rep"
        major = "Major: Philosophy & BCN"
        year = "Year: Senior"
	about = ""
      [[params.eboard.people]]
        img = "pfc2.jpg"
        title = "Nathan Baylis - Professional Fraternity Council Rep"
        major = "Major: Public Policy"
        year = "Year: Junior"
	about = ""

  [params.members]
    [[params.members.classes]]
      title = "Alpha"

      [[params.members.classes.names]]
        name = "Anu Nandi"
      [[params.members.classes.names]]
        name = "Nick Berg"  
      [[params.members.classes.names]]
        name = "Michael Keller"
      [[params.members.classes.names]]
        name = "Shirley Che" 
      [[params.members.classes.names]]
        name = "Sion Lee"
      [[params.members.classes.names]]
        name = "Katherine Goff"

    [[params.members.classes]]
      title = "Beta"

      [[params.members.classes.names]]
        name = "Ashley Munger"
      [[params.members.classes.names]]
        name = "Dim Mang"  
      [[params.members.classes.names]]
        name = "Elizabeth Chon"
      [[params.members.classes.names]]
        name = "Paula Laslou" 
      [[params.members.classes.names]]
        name = "Jennifer Meer"
      [[params.members.classes.names]]
        name = "Henry Milek"    

    [[params.members.classes]]
      title = "Gamma"

      [[params.members.classes.names]]
        name = "Sophia Kim"
      [[params.members.classes.names]]
        name = "Ivona Popova"  
      [[params.members.classes.names]]
        name = "Tatum Doyle"
      [[params.members.classes.names]]
        name = "Meera Kumar" 
      [[params.members.classes.names]]
        name = "Olivia Gunther"
      [[params.members.classes.names]]
        name = "Ben Blythe" 
      [[params.members.classes.names]]
        name = "Rachel Leung"
      [[params.members.classes.names]]
        name = "Riley Branigan"  
      [[params.members.classes.names]]
        name = "Sergio Villaseñor"
      [[params.members.classes.names]]
        name = "Brandon Pope" 
      [[params.members.classes.names]]
        name = "Jane Kim"
      [[params.members.classes.names]]
        name = "Sierra Welly"   
      [[params.members.classes.names]]
        name = "Jisoo Kang"
      [[params.members.classes.names]]
        name = "Lena Dreves" 
      [[params.members.classes.names]]
        name = "Margot Rice"
      [[params.members.classes.names]]
        name = "Mathilde Geannopulos" 

    [[params.members.classes]]
      title = "Delta"

      [[params.members.classes.names]]
        name = "Erin Hahn"
      [[params.members.classes.names]]
        name = "Brendan Killian"  
      [[params.members.classes.names]]
        name = "Caleb Hogeterp"
      [[params.members.classes.names]]
        name = "Daniel Bramhall" 
      [[params.members.classes.names]]
        name = "Izzie Kenhard"
      [[params.members.classes.names]]
        name = "Jordyn Houle" 
      [[params.members.classes.names]]
        name = "Kate Thompson"
      [[params.members.classes.names]]
        name = "Lexi LaChappa"  
      [[params.members.classes.names]]
        name = "Nathan Baylis"
      [[params.members.classes.names]]
        name = "Nick Guisinger" 
      [[params.members.classes.names]]
        name = "Noah Weingarden"
      [[params.members.classes.names]]
        name = "Sarah Charboneau"   
      [[params.members.classes.names]]
        name = "Suraj Sorab"
      [[params.members.classes.names]]
        name = "Sophia Vagnone" 
      [[params.members.classes.names]]
        name = "Stephanie Glenn"  

    [[params.members.classes]]
      title = "Epsilon"

      [[params.members.classes.names]]
        name = "Aleah Rogalsky"
      [[params.members.classes.names]]
        name = "Anna Marcus"  
      [[params.members.classes.names]]
        name = "Anthony Krempa"
      [[params.members.classes.names]]
        name = "Ashley Solle" 
      [[params.members.classes.names]]
        name = "Elizabeth Williams"
      [[params.members.classes.names]]
        name = "Isabella Gierlinger" 
      [[params.members.classes.names]]
        name = "Jordan Brady"
      [[params.members.classes.names]]
        name = "Julia Siegle"  
      [[params.members.classes.names]]
        name = "Lisi DiTullio"
      [[params.members.classes.names]]
        name = "Maria Graham" 
      [[params.members.classes.names]]
        name = "Morgan Bergstrom"
      [[params.members.classes.names]]
        name = "Peter Tolsma"   
      [[params.members.classes.names]]
        name = "Remy Farkas"
      [[params.members.classes.names]]
        name = "Riana Hardyniec" 
      [[params.members.classes.names]]
        name = "Riston Escher"
      [[params.members.classes.names]]
        name = "Warren Yu" 
      [[params.members.classes.names]]
        name = "Zachary Kolbusz"
      [[params.members.classes.names]]
        name = "Zayna Syed" 

  [params.call]
    enable = false
    title = "We design delightful digital experiences."
    paragraph = "Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve achieved for other clients, and meet our highly experienced Team who just love to design."

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Stop by for a visit"
      address = "North Main Street, Brooklyn Australia"
      email = "Email: contact@mail.com"
      phone = "Phone: +88 01672 506 744"
    [params.contact.gmaps]
      title = "We Also Count in Google Maps"
